// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Region struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
}

type RegionCell struct {
	RegionID int64 `json:"region_id"`
	X        int64 `json:"x"`
	Y        int64 `json:"y"`
}

type River struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RiverCell struct {
	RiverID int64 `json:"river_id"`
	X       int64 `json:"x"`
	Y       int64 `json:"y"`
	Ord     int64 `json:"ord"`
}
