// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetCellsInBounds(ctx context.Context, arg GetCellsInBoundsParams) ([]GetCellsInBoundsRow, error)
	GetRegion(ctx context.Context, id int64) (Region, error)
	GetRiverCellsInBounds(ctx context.Context, arg GetRiverCellsInBoundsParams) ([]GetRiverCellsInBoundsRow, error)
	InsertCell(ctx context.Context, arg InsertCellParams) error
	InsertRegion(ctx context.Context, arg InsertRegionParams) (Region, error)
	ListRegions(ctx context.Context) ([]Region, error)
	ListRivers(ctx context.Context) ([]River, error)
}

var _ Querier = (*Queries)(nil)
