// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regions.sql

package db

import (
	"context"
)

const getCellsInBounds = `-- name: GetCellsInBounds :many
SELECT rc.x, rc.y, r.kind, r.name, rc.elevation, rc.drainage
FROM region_cells rc
JOIN regions r ON r.id = rc.region_id
WHERE rc.x >= ? AND rc.x <= ? AND rc.y >= ? AND rc.y <= ?
`

type GetCellsInBoundsParams struct {
	X   int64 `json:"x"`
	X_2 int64 `json:"x_2"`
	Y   int64 `json:"y"`
	Y_2 int64 `json:"y_2"`
}

type GetCellsInBoundsRow struct {
	X         int64   `json:"x"`
	Y         int64   `json:"y"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Elevation float64 `json:"elevation"`
	Drainage  int64   `json:"drainage"`
}

func (q *Queries) GetCellsInBounds(ctx context.Context, arg GetCellsInBoundsParams) ([]GetCellsInBoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCellsInBounds,
		arg.X,
		arg.X_2,
		arg.Y,
		arg.Y_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCellsInBoundsRow{}
	for rows.Next() {
		var i GetCellsInBoundsRow
		if err := rows.Scan(
			&i.X,
			&i.Y,
			&i.Kind,
			&i.Name,
			&i.Elevation,
			&i.Drainage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegion = `-- name: GetRegion :one
SELECT id, name, kind FROM regions WHERE id = ?
`

func (q *Queries) GetRegion(ctx context.Context, id int64) (Region, error) {
	row := q.db.QueryRowContext(ctx, getRegion, id)
	var i Region
	err := row.Scan(&i.ID, &i.Name, &i.Kind)
	return i, err
}

const insertCell = `-- name: InsertCell :exec
INSERT INTO region_cells (region_id, x, y) VALUES (?, ?, ?)
`

type InsertCellParams struct {
	RegionID int64 `json:"region_id"`
	X        int64 `json:"x"`
	Y        int64 `json:"y"`
}

func (q *Queries) InsertCell(ctx context.Context, arg InsertCellParams) error {
	_, err := q.db.ExecContext(ctx, insertCell, arg.RegionID, arg.X, arg.Y)
	return err
}

const insertRegion = `-- name: InsertRegion :one
INSERT INTO regions (name, kind) VALUES (?, ?) RETURNING id, name, kind
`

type InsertRegionParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) InsertRegion(ctx context.Context, arg InsertRegionParams) (Region, error) {
	row := q.db.QueryRowContext(ctx, insertRegion, arg.Name, arg.Kind)
	var i Region
	err := row.Scan(&i.ID, &i.Name, &i.Kind)
	return i, err
}

const listRegions = `-- name: ListRegions :many
SELECT id, name, kind FROM regions ORDER BY id
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Region{}
	for rows.Next() {
		var i Region
		if err := rows.Scan(&i.ID, &i.Name, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
