// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rivers.sql

package db

import (
	"context"
)

const getRiverCellsInBounds = `-- name: GetRiverCellsInBounds :many
SELECT rc.river_id, rc.x, rc.y, rc.ord, r.name AS river_name
FROM river_cells rc
JOIN rivers r ON r.id = rc.river_id
WHERE rc.x >= ? AND rc.x <= ? AND rc.y >= ? AND rc.y <= ?
ORDER BY rc.river_id, rc.ord
`

type GetRiverCellsInBoundsParams struct {
	X   int64 `json:"x"`
	X_2 int64 `json:"x_2"`
	Y   int64 `json:"y"`
	Y_2 int64 `json:"y_2"`
}

type GetRiverCellsInBoundsRow struct {
	RiverID   int64  `json:"river_id"`
	X         int64  `json:"x"`
	Y         int64  `json:"y"`
	Ord       int64  `json:"ord"`
	RiverName string `json:"river_name"`
}

func (q *Queries) GetRiverCellsInBounds(ctx context.Context, arg GetRiverCellsInBoundsParams) ([]GetRiverCellsInBoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRiverCellsInBounds,
		arg.X,
		arg.X_2,
		arg.Y,
		arg.Y_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRiverCellsInBoundsRow{}
	for rows.Next() {
		var i GetRiverCellsInBoundsRow
		if err := rows.Scan(
			&i.RiverID,
			&i.X,
			&i.Y,
			&i.Ord,
			&i.RiverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRivers = `-- name: ListRivers :many
SELECT id, name FROM rivers ORDER BY id
`

func (q *Queries) ListRivers(ctx context.Context) ([]River, error) {
	rows, err := q.db.QueryContext(ctx, listRivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []River{}
	for rows.Next() {
		var i River
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
